// Inscritos de la Liga Nacional Absoluta 2026, sacados del Comunicado 06/2026 de la RFEP
// («Composición de los Equipos»). De cada patinador se guarda el nombre de pila y el primer apellido.
// Si cambia algún inscrito durante la temporada, se corrige aquí.

import type { ListaInscritos } from './inscritos'

export const LIGA_2026: ListaInscritos[] = [
  {
    id: 'liga-2026-1f',
    nombre: 'Liga Nacional 2026 · 1ª femenina',
    participantes: [
      { dorsal: 1, nombre: 'Amaiur Amillano', club: 'TXN' },
      { dorsal: 2, nombre: 'Greta Arriezu', club: 'TXN' },
      { dorsal: 3, nombre: 'Izadi Arteaga', club: 'TXN' },
      { dorsal: 4, nombre: 'Ruth Arza', club: 'TXN' },
      { dorsal: 5, nombre: 'Leire Chocarro', club: 'TXN' },
      { dorsal: 6, nombre: 'Uxue Cruz', club: 'TXN' },
      { dorsal: 7, nombre: 'Arrate Jauregui', club: 'TXN' },
      { dorsal: 8, nombre: 'Liz Lorea', club: 'TXN' },
      { dorsal: 9, nombre: 'Ana Villegas', club: 'TXN' },
      { dorsal: 10, nombre: 'Amaia Zubiri', club: 'TXN' },
      { dorsal: 11, nombre: 'Luisa Ayala', club: 'SJN' },
      { dorsal: 12, nombre: 'Eider Liras', club: 'SJN' },
      { dorsal: 13, nombre: 'Paula Rodriguez', club: 'SJN' },
      { dorsal: 14, nombre: 'Aroa Ruiz', club: 'SJN' },
      { dorsal: 15, nombre: 'Marta Sanchez', club: 'SJN' },
      { dorsal: 16, nombre: 'Uxue Sola', club: 'SJN' },
      { dorsal: 17, nombre: 'Sara Arregui', club: 'ARG' },
      { dorsal: 18, nombre: 'María Cardenas', club: 'ARG' },
      { dorsal: 19, nombre: 'Abril del Rio', club: 'ARG' },
      { dorsal: 20, nombre: 'Daniela Farelo', club: 'ARG' },
      { dorsal: 21, nombre: 'Ana Humanes', club: 'ARG' },
      { dorsal: 22, nombre: 'Emilia Rangel', club: 'ARG' },
      { dorsal: 23, nombre: 'Paula Espin', club: 'PRT' },
      { dorsal: 24, nombre: 'Luisa Gonzalez', club: 'PRT' },
      { dorsal: 25, nombre: 'Noelia Martinez', club: 'PRT' },
      { dorsal: 26, nombre: 'Teresa Moreno', club: 'PRT' },
      { dorsal: 27, nombre: 'Ona Rodriguez', club: 'PRT' },
      { dorsal: 28, nombre: 'Monica Seoane', club: 'PRT' },
      { dorsal: 29, nombre: 'Mireia Tellez', club: 'PRT' },
      { dorsal: 30, nombre: 'Alba Alvarez', club: 'SIE' },
      { dorsal: 31, nombre: 'Cira Alvarez', club: 'SIE' },
      { dorsal: 32, nombre: 'Alba Antolin', club: 'SIE' },
      { dorsal: 33, nombre: 'Oliegtnis Mercado', club: 'SIE' },
      { dorsal: 34, nombre: 'Sara Cabrera', club: 'CDT' },
      { dorsal: 35, nombre: 'Leire Gömez', club: 'CDT' },
      { dorsal: 36, nombre: 'Sandra Martin', club: 'CDT' },
      { dorsal: 37, nombre: 'Angélica Rosero', club: 'CDT' },
      { dorsal: 38, nombre: 'Yirley Urrego', club: 'CDT' },
      { dorsal: 39, nombre: 'Iranzu Arriaga', club: 'CDA' },
      { dorsal: 40, nombre: 'Mar Ayzagar', club: 'CDA' },
      { dorsal: 41, nombre: 'Nerea Ceballos', club: 'CDA' },
      { dorsal: 42, nombre: 'Nahia Magdaleno', club: 'CDA' },
      { dorsal: 43, nombre: 'Marta Martin', club: 'CDA' },
      { dorsal: 44, nombre: 'Ane Miqueleiz', club: 'CDA' },
      { dorsal: 45, nombre: 'Yaiza Salinas', club: 'CDA' },
      { dorsal: 46, nombre: 'Marina Bilbao', club: 'PLY' },
      { dorsal: 47, nombre: 'Selina Casais', club: 'PLY' },
      { dorsal: 48, nombre: 'Aitana Gonzalez', club: 'PLY' },
      { dorsal: 49, nombre: 'Claudia Lobato', club: 'PLY' },
      { dorsal: 50, nombre: 'Sheila Posada', club: 'PLY' },
      { dorsal: 51, nombre: 'Almudena Blanco', club: 'PAI' },
      { dorsal: 52, nombre: 'Nora Carné', club: 'PAI' },
      { dorsal: 53, nombre: 'Ainhoa Gramaje', club: 'PAI' },
      { dorsal: 54, nombre: 'Sara Marí', club: 'PAI' },
      { dorsal: 55, nombre: 'Eva Villena', club: 'PAI' },
      { dorsal: 56, nombre: 'Katherine Cardona', club: 'SDP' },
      { dorsal: 57, nombre: 'Alba Coca', club: 'SDP' },
      { dorsal: 58, nombre: 'Silvia Garcia', club: 'SDP' },
      { dorsal: 59, nombre: 'Nahia Montero', club: 'SDP' },
      { dorsal: 60, nombre: 'Laura Montes', club: 'SDP' },
      { dorsal: 61, nombre: 'Paula Portela', club: 'SDP' },
    ],
  },
  {
    id: 'liga-2026-1m',
    nombre: 'Liga Nacional 2026 · 1ª masculina',
    participantes: [
      { dorsal: 62, nombre: 'Iker Bretón', club: 'CDT' },
      { dorsal: 63, nombre: 'Miguel Carrillo', club: 'CDT' },
      { dorsal: 64, nombre: 'Héctor Escrihuela', club: 'CDT' },
      { dorsal: 65, nombre: 'Daniel Garro', club: 'CDT' },
      { dorsal: 66, nombre: 'Jesus Hernandez', club: 'CDT' },
      { dorsal: 67, nombre: 'Oiver Lindenskov', club: 'CDT' },
      { dorsal: 68, nombre: 'Daniel Milagros', club: 'CDT' },
      { dorsal: 69, nombre: 'Manel Robla', club: 'CDT' },
      { dorsal: 70, nombre: 'Sergi Alvarez', club: 'PRT' },
      { dorsal: 71, nombre: 'Dayan Diaz', club: 'PRT' },
      { dorsal: 72, nombre: 'Rafael Heredia', club: 'PRT' },
      { dorsal: 73, nombre: 'Nil Llop', club: 'PRT' },
      { dorsal: 74, nombre: 'Chistopfher Lopez', club: 'PRT' },
      { dorsal: 75, nombre: 'Gaston Moreno', club: 'PRT' },
      { dorsal: 76, nombre: 'Iván Roldán', club: 'PRT' },
      { dorsal: 77, nombre: 'Aaron Beneitez', club: 'TXN' },
      { dorsal: 78, nombre: 'Julen Colmenero', club: 'TXN' },
      { dorsal: 79, nombre: 'Iker Escalada', club: 'TXN' },
      { dorsal: 80, nombre: 'Jonathan Galar', club: 'TXN' },
      { dorsal: 81, nombre: 'Jose Gonzalez', club: 'TXN' },
      { dorsal: 82, nombre: 'Amaiur Johnston', club: 'TXN' },
      { dorsal: 83, nombre: 'Karlos Lorea', club: 'TXN' },
      { dorsal: 84, nombre: 'Mikel Medina', club: 'TXN' },
      { dorsal: 85, nombre: 'Iñaki Paternain', club: 'TXN' },
      { dorsal: 86, nombre: 'Joan Valero', club: 'TXN' },
      { dorsal: 87, nombre: 'Raúl Couto', club: 'RBD' },
      { dorsal: 88, nombre: 'Chirstian de la Cruz', club: 'RBD' },
      { dorsal: 89, nombre: 'John Luna', club: 'RBD' },
      { dorsal: 90, nombre: 'Adrián Suárez', club: 'RBD' },
      { dorsal: 91, nombre: 'Manuel Taibo', club: 'RBD' },
      { dorsal: 92, nombre: 'Carlos Tarazona', club: 'RBD' },
      { dorsal: 93, nombre: 'Xoel Vilariño', club: 'RBD' },
      { dorsal: 94, nombre: 'Gaizka Blanco', club: 'CDA' },
      { dorsal: 95, nombre: 'Hugo Breton', club: 'CDA' },
      { dorsal: 96, nombre: 'Oier Lara', club: 'CDA' },
      { dorsal: 97, nombre: 'Unai Lara', club: 'CDA' },
      { dorsal: 98, nombre: 'Javier Larrasoain', club: 'CDA' },
      { dorsal: 99, nombre: 'Lucas Orzanco', club: 'CDA' },
      { dorsal: 100, nombre: 'Omar García', club: 'LGK' },
      { dorsal: 101, nombre: 'Arian Hualde', club: 'LGK' },
      { dorsal: 102, nombre: 'Ioritz Marqués', club: 'LGK' },
      { dorsal: 103, nombre: 'Ibai Marquina', club: 'LGK' },
      { dorsal: 104, nombre: 'Borja Navarro', club: 'LGK' },
      { dorsal: 105, nombre: 'Asier Perales', club: 'LGK' },
      { dorsal: 106, nombre: 'Sergio Tere', club: 'LGK' },
      { dorsal: 107, nombre: 'Julen Urkizar', club: 'LGK' },
      { dorsal: 108, nombre: 'Aitor Vacas', club: 'LGK' },
      { dorsal: 109, nombre: 'Ximon Villalobos', club: 'LGK' },
      { dorsal: 110, nombre: 'Unai Villalobos', club: 'LGK' },
      { dorsal: 111, nombre: 'Fabricio Erviti', club: 'RVS' },
      { dorsal: 112, nombre: 'Jurgen Forero', club: 'RVS' },
      { dorsal: 113, nombre: 'Raul Jardim', club: 'RVS' },
      { dorsal: 114, nombre: 'Ignacio Moran', club: 'RVS' },
      { dorsal: 115, nombre: 'David Quintero', club: 'RVS' },
      { dorsal: 116, nombre: 'Alexander Rezzonico', club: 'RVS' },
      { dorsal: 117, nombre: 'Gabriel Barata', club: 'ALM' },
      { dorsal: 118, nombre: 'Alejandro Cortes', club: 'ALM' },
      { dorsal: 119, nombre: 'Gustavo Murillo', club: 'ALM' },
      { dorsal: 120, nombre: 'Pau Peña', club: 'ALM' },
      { dorsal: 121, nombre: 'Juan Peña', club: 'ALM' },
      { dorsal: 122, nombre: 'Manel Perez', club: 'ALM' },
      { dorsal: 123, nombre: 'Marc Sales', club: 'ALM' },
      { dorsal: 124, nombre: 'Adrian Alonso', club: 'RLL' },
      { dorsal: 125, nombre: 'Rodrigo Casado', club: 'RLL' },
      { dorsal: 126, nombre: 'Borja Iglesias', club: 'RLL' },
      { dorsal: 127, nombre: 'Hugo Martin', club: 'RLL' },
      { dorsal: 128, nombre: 'Alvaro Nieto', club: 'RLL' },
      { dorsal: 129, nombre: 'Jorge Revilla', club: 'RLL' },
      { dorsal: 130, nombre: 'Unai Baztán', club: 'SJN' },
      { dorsal: 131, nombre: 'Asier Dufur', club: 'SJN' },
      { dorsal: 132, nombre: 'Juan Fernandez', club: 'SJN' },
      { dorsal: 133, nombre: 'Miguel Fernandez', club: 'SJN' },
      { dorsal: 134, nombre: 'Iker Garcia', club: 'SJN' },
      { dorsal: 135, nombre: 'Adrián Gómez', club: 'SJN' },
      { dorsal: 136, nombre: 'Jon Senosiain', club: 'SJN' },
      { dorsal: 137, nombre: 'Iñaki Unanua', club: 'SJN' },
      { dorsal: 138, nombre: 'Javier Unanua', club: 'SJN' },
    ],
  },
  {
    id: 'liga-2026-2f',
    nombre: 'Liga Nacional 2026 · 2ª femenina',
    participantes: [
      { dorsal: 139, nombre: 'Sara Bedia', club: 'ASP' },
      { dorsal: 140, nombre: 'Desiree Castellanos', club: 'ASP' },
      { dorsal: 141, nombre: 'Daniela Diaz', club: 'ASP' },
      { dorsal: 142, nombre: 'Andrea Fernandez', club: 'ASP' },
      { dorsal: 143, nombre: 'Yaiza Lopez', club: 'ASP' },
      { dorsal: 144, nombre: 'Leyre Montiel', club: 'ASP' },
      { dorsal: 145, nombre: 'Irene Cabrero', club: '2M6' },
      { dorsal: 146, nombre: 'Luna Dominguez', club: '2M6' },
      { dorsal: 147, nombre: 'Claudia Langa', club: '2M6' },
      { dorsal: 148, nombre: 'Nerea Langa', club: '2M6' },
      { dorsal: 149, nombre: 'Leyre Pallares', club: '2M6' },
      { dorsal: 150, nombre: 'Amaiur Amenábar', club: 'LGK' },
      { dorsal: 151, nombre: 'Leire Bolaños', club: 'LGK' },
      { dorsal: 152, nombre: 'Ainhoa Callén', club: 'LGK' },
      { dorsal: 153, nombre: 'Iraia Ema', club: 'LGK' },
      { dorsal: 154, nombre: 'Eider Lakuntza', club: 'LGK' },
      { dorsal: 155, nombre: 'Iradi Lakuntza', club: 'LGK' },
      { dorsal: 156, nombre: 'Uxue Pascual', club: 'LGK' },
      { dorsal: 157, nombre: 'Claudia Batalla', club: 'ALM' },
      { dorsal: 158, nombre: 'Nathalia Bermudez', club: 'ALM' },
      { dorsal: 159, nombre: 'Balma Blasco', club: 'ALM' },
      { dorsal: 160, nombre: 'Lola Estrada', club: 'ALM' },
      { dorsal: 161, nombre: 'Carla Pauner', club: 'ALM' },
      { dorsal: 162, nombre: 'Naiara Vargas', club: 'ALM' },
      { dorsal: 163, nombre: 'Adriana Almodovar', club: 'CDT' },
      { dorsal: 164, nombre: 'Nadia Colás', club: 'CDT' },
      { dorsal: 165, nombre: 'Ainara Liceaga', club: 'CDT' },
      { dorsal: 166, nombre: 'Alazne Lluch', club: 'CDT' },
      { dorsal: 167, nombre: 'Sara Orozco', club: 'CDT' },
      { dorsal: 168, nombre: 'Andrea Boedo', club: 'RBD' },
      { dorsal: 169, nombre: 'Ana Canosa', club: 'RBD' },
      { dorsal: 170, nombre: 'Alba Eiroa', club: 'RBD' },
      { dorsal: 171, nombre: 'Laura Palmeiro', club: 'RBD' },
      { dorsal: 172, nombre: 'Alua Ramon', club: 'RBD' },
      { dorsal: 173, nombre: 'Amaya Santos', club: 'RBD' },
      { dorsal: 174, nombre: 'Adriana Bernarte', club: 'SJN' },
      { dorsal: 175, nombre: 'Lucia Crespo', club: 'SJN' },
      { dorsal: 176, nombre: 'Carolina Garro', club: 'SJN' },
      { dorsal: 177, nombre: 'Avril Larrea', club: 'SJN' },
      { dorsal: 178, nombre: 'Haizea Laspeñas', club: 'SJN' },
      { dorsal: 179, nombre: 'Arai Leatxe', club: 'SJN' },
      { dorsal: 180, nombre: 'Anne Leon', club: 'SJN' },
      { dorsal: 181, nombre: 'Nerea Otermin', club: 'SJN' },
      { dorsal: 182, nombre: 'Uxue Somovilla', club: 'SJN' },
      { dorsal: 183, nombre: 'Leire Valle', club: 'SJN' },
      { dorsal: 184, nombre: 'Uxue Errandonea', club: 'CDA' },
      { dorsal: 185, nombre: 'Martina Lopez', club: 'CDA' },
      { dorsal: 186, nombre: 'Carla Martino', club: 'CDA' },
      { dorsal: 187, nombre: 'Alba Muniz', club: 'CDA' },
      { dorsal: 188, nombre: 'Irati Salinas', club: 'CDA' },
      { dorsal: 189, nombre: 'Julene Vera', club: 'CDA' },
      { dorsal: 190, nombre: 'Naiara Zudaire', club: 'CDA' },
      { dorsal: 191, nombre: 'Anny Angulo', club: 'PTO' },
      { dorsal: 192, nombre: 'Celia Cerisola', club: 'PTO' },
      { dorsal: 193, nombre: 'Llanos Fernandez', club: 'PTO' },
      { dorsal: 194, nombre: 'Eva Fernandez', club: 'PTO' },
      { dorsal: 195, nombre: 'Adriana Cantillo', club: 'NOV' },
      { dorsal: 196, nombre: 'Ella Méndez', club: 'NOV' },
      { dorsal: 197, nombre: 'Llara Menéndez', club: 'NOV' },
      { dorsal: 198, nombre: 'Irene Reyes', club: 'NOV' },
      { dorsal: 199, nombre: 'Paula Vizán', club: 'NOV' },
    ],
  },
  {
    id: 'liga-2026-2m',
    nombre: 'Liga Nacional 2026 · 2ª masculina',
    participantes: [
      { dorsal: 200, nombre: 'Kevin Arias', club: 'MAR' },
      { dorsal: 201, nombre: 'Mario Cardesa', club: 'MAR' },
      { dorsal: 202, nombre: 'Diego Casas', club: 'MAR' },
      { dorsal: 203, nombre: 'Gonzalo Ferraz', club: 'MAR' },
      { dorsal: 204, nombre: 'Carlos Galve', club: 'MAR' },
      { dorsal: 205, nombre: 'Carlos Herrera', club: 'MAR' },
      { dorsal: 206, nombre: 'Daniel Laiglesia', club: 'MAR' },
      { dorsal: 207, nombre: 'Alvaro Benita', club: 'CDT' },
      { dorsal: 208, nombre: 'Marc Escrihuela', club: 'CDT' },
      { dorsal: 209, nombre: 'Lucas Lucena', club: 'CDT' },
      { dorsal: 210, nombre: 'Jorge Marti', club: 'CDT' },
      { dorsal: 211, nombre: 'Hugo Martin', club: 'CDT' },
      { dorsal: 212, nombre: 'Pasqual Pons', club: 'CDT' },
      { dorsal: 213, nombre: 'Hugo Sanchez', club: 'CDT' },
      { dorsal: 214, nombre: 'Angel Urrego', club: 'CDT' },
      { dorsal: 215, nombre: 'Jesus Bernal', club: 'PRT' },
      { dorsal: 216, nombre: 'David Camargo', club: 'PRT' },
      { dorsal: 217, nombre: 'Pau Chorro', club: 'PRT' },
      { dorsal: 218, nombre: 'Adrià Fernández', club: 'PRT' },
      { dorsal: 219, nombre: 'Oriol Gisbert', club: 'PRT' },
      { dorsal: 220, nombre: 'Samuel Granada', club: 'PRT' },
      { dorsal: 221, nombre: 'Juliá Laporta', club: 'PRT' },
      { dorsal: 222, nombre: 'Pau Puig', club: 'PRT' },
      { dorsal: 223, nombre: 'Sebastian Rincon', club: 'PRT' },
      { dorsal: 224, nombre: 'Iker Ruiz', club: 'PRT' },
      { dorsal: 225, nombre: 'Fernando Santos', club: 'PRT' },
      { dorsal: 226, nombre: 'Salvador Barreiro', club: 'NVD' },
      { dorsal: 227, nombre: 'Santiago Garcia', club: 'NVD' },
      { dorsal: 228, nombre: 'Alvaro Rey', club: 'NVD' },
      { dorsal: 229, nombre: 'Pelayo Santiago', club: 'NVD' },
      { dorsal: 230, nombre: 'Mikel Alzueta', club: 'CDA' },
      { dorsal: 231, nombre: 'Unax Ayala', club: 'CDA' },
      { dorsal: 232, nombre: 'Iosu Blanco', club: 'CDA' },
      { dorsal: 233, nombre: 'Iago Blanco', club: 'CDA' },
      { dorsal: 234, nombre: 'Aimar Foncillas', club: 'CDA' },
      { dorsal: 235, nombre: 'Inar Mena', club: 'CDA' },
      { dorsal: 236, nombre: 'Asier Valle', club: 'CDA' },
      { dorsal: 237, nombre: 'Jesus Colmenares', club: 'ARG' },
      { dorsal: 238, nombre: 'Darius Corrut', club: 'ARG' },
      { dorsal: 239, nombre: 'Unai Fernandez-Izaguirre', club: 'ARG' },
      { dorsal: 240, nombre: 'Robert Girigan', club: 'ARG' },
      { dorsal: 241, nombre: 'Miguel Merino', club: 'ARG' },
      { dorsal: 242, nombre: 'Samuel Ortiz', club: 'ARG' },
      { dorsal: 243, nombre: 'Diego Perez', club: 'ARG' },
      { dorsal: 244, nombre: 'Oscar Quejido', club: 'ARG' },
      { dorsal: 245, nombre: 'Osmani Reina', club: 'ARG' },
      { dorsal: 246, nombre: 'Alejandro Restrepo', club: 'ARG' },
      { dorsal: 247, nombre: 'Miguel Rubio', club: 'ARG' },
      { dorsal: 248, nombre: 'Aitor Sanchez', club: 'ARG' },
      { dorsal: 249, nombre: 'Iván Galar', club: 'ALA' },
      { dorsal: 250, nombre: 'Alejandro Martín', club: 'ALA' },
      { dorsal: 251, nombre: 'Francisco Moyano', club: 'ALA' },
      { dorsal: 252, nombre: 'Pablo Muñoz', club: 'ALA' },
      { dorsal: 253, nombre: 'Daniel Muñoz', club: 'ALA' },
      { dorsal: 254, nombre: 'Luis Socorro', club: 'ALA' },
      { dorsal: 255, nombre: 'Alejandro Yáñez', club: 'ALA' },
      { dorsal: 256, nombre: 'Pablo Cal', club: 'SDP' },
      { dorsal: 257, nombre: 'Mario de Diego', club: 'SDP' },
      { dorsal: 258, nombre: 'Diego Garcia', club: 'SDP' },
      { dorsal: 259, nombre: 'Jaime Gayo', club: 'SDP' },
      { dorsal: 260, nombre: 'Miguel Gayo', club: 'SDP' },
      { dorsal: 261, nombre: 'Yago Ivan', club: 'SDP' },
      { dorsal: 262, nombre: 'Fernando Mejia', club: 'SDP' },
      { dorsal: 263, nombre: 'Ivan Platas', club: 'SDP' },
      { dorsal: 264, nombre: 'Pablo Aguilera', club: 'ALM' },
      { dorsal: 265, nombre: 'Jorge Aguilera', club: 'ALM' },
      { dorsal: 266, nombre: 'Carlos Delgado', club: 'ALM' },
      { dorsal: 267, nombre: 'Raul Martin', club: 'ALM' },
      { dorsal: 268, nombre: 'Marc Mas', club: 'ALM' },
      { dorsal: 269, nombre: 'Alberto Masso', club: 'ALM' },
      { dorsal: 270, nombre: 'Adrian Portilla', club: 'ALM' },
      { dorsal: 271, nombre: 'Marcos Alonso', club: 'RLL' },
      { dorsal: 272, nombre: 'Ivan Bilenets', club: 'RLL' },
      { dorsal: 273, nombre: 'Miguel Cosgaya', club: 'RLL' },
      { dorsal: 274, nombre: 'Martin Diez', club: 'RLL' },
      { dorsal: 275, nombre: 'Martin Fullaondo', club: 'RLL' },
      { dorsal: 276, nombre: 'Ismael Hernandez', club: 'RLL' },
      { dorsal: 277, nombre: 'Hector Merino', club: 'RLL' },
      { dorsal: 278, nombre: 'Nivaldo Orozco', club: 'RLL' },
      { dorsal: 279, nombre: 'Nicolas Rodriguez', club: 'RLL' },
      { dorsal: 280, nombre: 'Victor Alvarez', club: 'NOV' },
      { dorsal: 281, nombre: 'Yoel Álvarez', club: 'NOV' },
      { dorsal: 282, nombre: 'Pablo González', club: 'NOV' },
      { dorsal: 283, nombre: 'Álvaro Picazo', club: 'NOV' },
      { dorsal: 284, nombre: 'Enrique Fernandez', club: 'GRX' },
      { dorsal: 285, nombre: 'Miguel Medina', club: 'GRX' },
      { dorsal: 286, nombre: 'Miguel Pez', club: 'GRX' },
      { dorsal: 287, nombre: 'Jaime Rios', club: 'GRX' },
      { dorsal: 288, nombre: 'Nicolas Suarez', club: 'GRX' },
    ],
  },
]
