// Todos los textos de la interfaz en un único sitio, para poder traducir la web sin tocar las pantallas.
export const TEXTOS = {
  crearCarrera: {
    titulo: 'Nueva carrera',
    nombre: 'Nombre de la carrera',
    nombreEjemplo: 'Liga Nacional, jornada 3',
    vueltasTotales: 'Vueltas totales',
    primerSprint: 'Primer sprint a falta de',
    frecuencia: 'Sprints',
    cadaVuelta: 'Cada vuelta',
    unaSiUnaNo: 'Una sí y una no',
    puntosIntermedio: 'Puntos en sprints intermedios',
    puntosFinal: 'Puntos en el sprint final',
    dorsales: 'Dorsales',
    dorsalesAyuda: 'Rangos y números sueltos, por ejemplo: 1-24, 30, 31',
    resumenSprints: 'Sprints a falta de',
    final: 'final',
    participantes: 'participantes',
    empezar: 'Empezar carrera',
  },
  carrera: {
    nuevaCarrera: 'Nueva carrera',
    sprintAFalta: 'Sprint a falta de',
    sprintFinal: 'Sprint final',
    quedan: 'Sprints que quedan',
    puesto: (n: number) => `${n}.º`,
    deshacer: 'Deshacer',
    sinRegistrar: 'Sprint sin registrar',
    ultimo: 'Último registrado',
    vacio: 'sin registrar',
    terminada: 'Todos los sprints registrados',
    confirmarSalir: '¿Empezar una carrera nueva? Esta se borrará del dispositivo.',
  },
  incidencias: {
    ayuda: 'Mantén pulsado un dorsal para doblajes, abandonos y descalificaciones.',
    titulo: (dorsal: number) => `Dorsal ${dorsal}`,
    dobladoPeloton: 'Doblado por el pelotón',
    dobladoPelotonDetalle: 'Queda eliminado',
    dobladoEscapada: 'Doblado por una escapada',
    dobladoEscapadaDetalle: 'Pierde sus puntos, sigue en carrera',
    abandono: 'Abandona',
    descalificacion: 'Descalificado',
    cancelar: 'Cancelar',
    escapadaDobla: 'La escapada dobla al pelotón',
    tocaEscapados: 'Toca los dorsales de la escapada',
    escapadaDetalle: 'Todos los demás pierden sus puntos y siguen en carrera.',
    confirmar: 'Confirmar',
    fuera: 'fuera',
  },
  historial: {
    abrir: 'Historial y correcciones',
    titulo: 'Historial',
    vacio: 'Todavía no se ha anotado nada.',
    corregir: 'Corregir',
    borrar: 'Borrar',
    confirmarBorrar: (texto: string) => `¿Borrar «${texto}»?`,
    cerrar: 'Cerrar',
    corrigiendo: 'Corrigiendo',
    ayudaCorregir: 'Toca los dorsales en el orden correcto. Si lo dejas vacío, queda sin registrar.',
    guardar: 'Guardar corrección',
    cancelar: 'Cancelar',
  },
  final: {
    terminar: 'Terminar carrera',
    titulo: 'Resultados',
    empate: (puntos: number) => `Empate a ${puntos} puntos`,
    ayudaEmpate: 'Toca los dorsales en el orden en que cruzaron la meta en la última vuelta.',
    borrarEmpate: 'Empezar de nuevo',
    rehacerEmpates: 'Corregir desempates',
    pendiente: 'Faltan empates por resolver: el orden de los empatados puede no ser el definitivo.',
    compartir: 'Compartir (WhatsApp…)',
    copiar: 'Copiar texto',
    copiado: 'Copiado',
    volver: 'Volver a la carrera',
    sinPuntos: (n: number) => (n === 1 ? '1 patinador sin puntos' : `${n} patinadores sin puntos`),
    puntos: 'pt',
  },
  clasificacion: {
    titulo: 'Clasificación',
    enJuego: 'Puntos en juego',
    nadie: 'Todavía no ha puntuado nadie.',
    lider: 'Líder',
    asegurado: 'Asegurado*',
    fueraDeAlcance: 'Sin opciones',
    noTerminan: 'No terminan',
    eliminado: 'eliminado',
    abandono: 'abandono',
    descalificado: 'descalificado',
    notaAsegurado: '* Salvo doblaje o descalificación.',
  },
}
