// Todos los textos de la interfaz en un único sitio, para poder traducir la web sin tocar las pantallas.
export const TEXTOS = {
  crearCarrera: {
    titulo: 'Nueva carrera',
    nombre: 'Nombre de la carrera',
    nombreEjemplo: 'Liga Nacional, jornada 3',
    vueltasTotales: 'Vueltas totales',
    primerSprint: 'Primer sprint a falta de',
    frecuencia: 'Sprints',
    cadaVuelta: 'Cada vuelta',
    unaSiUnaNo: 'Una sí y una no',
    puntosIntermedio: 'Puntos por sprint',
    puntosFinal: 'Puntos del sprint final',
    competicion: 'Competición',
    inscritos: (n: number, deSanJuan: number) => `${n} inscritos · ${deSanJuan > 0 ? `${deSanJuan} de San Juan` : 'sin San Juan'}`,
    otraCarrera: 'Otra carrera',
    otraCarreraAyuda: 'Escribir los dorsales',
    nombreAyuda: 'Se rellena al elegir la división. Puedes añadir la jornada.',
    resumen: 'Resumen',
    sinSprints: 'Rellena las vueltas para ver los sprints.',
    enClubes: (n: number) => `inscritos en ${n} clubes`,
    elegirQuienCorre: 'Elegir quién corre',
    deSanJuan: (n: number) => `de los ${n} de San Juan`,
    queDivision: '¿Qué división corre?',
    dorsales: 'Dorsales',
    dorsalesAyuda: 'Rangos y números sueltos, por ejemplo: 1-24, 30, 31',
    resumenSprints: 'Sprints a falta de',
    final: 'final',
    participantes: 'participantes',
    empezar: 'Empezar carrera',
    equipo: 'Equipo',
    sinEquipo: 'Ninguno',
    gestionarEquipos: 'Gestionar equipos',
    delEquipo: 'del equipo',
  },
  convocatoria: {
    titulo: '¿Quién corre?',
    marcarTodos: 'Marcar todos',
    volver: 'Volver',
    corre: 'Corre',
    noCorre: 'No corre',
    deCorren: (total: number) => `de ${total} corren`,
    empezar: 'Empezar carrera',
  },
  historialCarreras: {
    abrir: (n: number) => `Carreras anteriores (${n})`,
    titulo: 'Carreras anteriores',
    ninguna: 'Todavía no hay ninguna carrera terminada.',
    ganador: 'Gana',
    volver: 'Volver',
    borrar: 'Borrar del historial',
    confirmarBorrar: (nombre: string) => `¿Borrar «${nombre}» del historial? No se puede deshacer.`,
    guardada: 'Guardada en «Carreras anteriores».',
  },
  juegos: {
    titulo: 'Equipos y dorsales',
    ayuda: 'Un juego por tipo de competición y temporada, con el dorsal de cada patinador del equipo.',
    ninguno: 'Todavía no hay ninguno.',
    nuevo: 'Nuevo juego de dorsales',
    editar: 'Editar',
    duplicar: 'Duplicar',
    copia: (nombre: string) => `${nombre} (copia)`,
    patinadores: (n: number) => (n === 1 ? '1 patinador' : `${n} patinadores`),
    nombre: 'Competición y temporada',
    nombreEjemplo: 'Liga Nacional 2026',
    miembros: 'Patinadores del equipo',
    miembrosAyuda: 'Uno por línea: dorsal y nombre, por ejemplo «12 Adrián».',
    guardar: 'Guardar',
    borrar: 'Borrar',
    confirmarBorrar: (nombre: string) => `¿Borrar «${nombre}»?`,
    cancelar: 'Cancelar',
    volver: 'Volver',
  },
  carrera: {
    nuevaCarrera: 'Nueva carrera',
    vista: 'Ordenar la rejilla',
    porEquipos: 'Por equipos',
    porDorsal: 'Por dorsal',
    sprintAFalta: 'Sprint a falta de',
    sprintFinal: 'Sprint final',
    quedan: 'Quedan',
    enJuego: 'En juego',
    ultimaVuelta: 'Última vuelta',
    puesto: (n: number) => `${n}.º`,
    deshacer: 'Deshacer',
    sinRegistrar: 'Sprint sin registrar',
    ultimo: 'Último registrado',
    vacio: 'sin registrar',
    terminada: 'Todos los sprints registrados',
    confirmarSalir: '¿Empezar una carrera nueva? Esta se borrará del dispositivo.',
    menu: 'Menú',
    cerrar: 'Cerrar',
    sprints: 'Sprints de la carrera',
    ahora: 'ahora',
    final: 'Final',
    cuenta: (quedan: number, enJuego: number) => `quedan ${quedan} · en juego ${enJuego}`,
    // Etiquetas cortas de los botones que hay debajo de Deshacer.
    sinRegistrarCorto: 'Sin registrar',
    escapadaCorto: 'Escapada',
    historialCorto: 'Historial',
  },
  incidencias: {
    ayuda: 'Mantén pulsado un dorsal para doblajes, abandonos y descalificaciones.',
    titulo: (dorsal: number) => `Dorsal ${dorsal}`,
    dobladoPeloton: 'Doblado por el pelotón',
    dobladoPelotonDetalle: 'Queda eliminado',
    dobladoEscapada: 'Doblado por una escapada',
    dobladoEscapadaDetalle: 'Pierde sus puntos, sigue en carrera',
    abandono: 'Abandona',
    descalificacion: 'Descalificado',
    cancelar: 'Cancelar',
    escapadaDobla: 'La escapada dobla al pelotón',
    tocaEscapados: 'Toca los dorsales de la escapada',
    escapadaDetalle: 'Todos los demás pierden sus puntos y siguen en carrera.',
    confirmar: 'Confirmar',
  },
  historial: {
    abrir: 'Historial y correcciones',
    titulo: 'Historial',
    vacio: 'Todavía no se ha anotado nada.',
    corregir: 'Corregir',
    borrar: 'Borrar',
    confirmarBorrar: (texto: string) => `¿Borrar «${texto}»?`,
    cerrar: 'Cerrar',
    corrigiendo: 'Corrigiendo',
    ayudaCorregir: 'Toca los dorsales en el orden correcto. Si lo dejas vacío, queda sin registrar.',
    guardar: 'Guardar corrección',
    cancelar: 'Cancelar',
  },
  final: {
    terminar: 'Terminar carrera',
    titulo: 'Resultados',
    empate: (puntos: number) => `Empate a ${puntos} puntos`,
    ayudaEmpate: 'Toca los dorsales en el orden en que cruzaron la meta en la última vuelta.',
    borrarEmpate: 'Empezar de nuevo',
    rehacerEmpates: 'Corregir desempates',
    pendiente: 'Faltan empates por resolver: el orden de los empatados puede no ser el definitivo.',
    compartir: 'Compartir (WhatsApp…)',
    compartirImagen: 'Compartir como imagen',
    copiar: 'Copiar texto',
    copiado: 'Copiado',
    volver: 'Volver a la carrera',
    sinPuntos: (n: number) => (n === 1 ? '1 patinador sin puntos' : `${n} patinadores sin puntos`),
    puntos: 'pt',
  },
  clasificacion: {
    titulo: 'Clasificación',
    enJuego: 'Puntos en juego',
    nadie: 'Todavía no ha puntuado nadie.',
    noTerminan: 'No terminan',
    eliminado: 'eliminado',
    abandono: 'abandono',
    descalificado: 'descalificado',
    columnas: 'pts',
  },
  // Códigos cortos de la torre para los que no terminan, como el OUT de la F1.
  codigos: { eliminado: 'DOB', abandono: 'ABA', descalificado: 'DSQ' },
}
